 on:
  workflow_dispatch:

name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Production
        run: |
          echo "Deploying to production server..."
          # Aqui, você pode colocar o comando de deploy para seu ambiente de produção
          # Exemplo: `ssh user@server 'deploy.sh'`
