name: CI - Python App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout do código
        uses: actions/checkout@v3

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ✅ Rodar testes
        run: |
          # Use pytest se estiver usando-o; senão, use unittest
          if [ -f pytest.ini ] || [ -d tests ]; then
            pytest
          else
            python -m unittest discover
          fi
